resources:
- repo: self
stages:
- stage: DocfxBuild
  jobs:
  - job: Docfx
    displayName: BuildStaticFiles
    pool:
      name: Default
    steps:
    - task: UseNode@1
      inputs:
        version: '12.10.0'
    - task: chrismason.vsts-docfxtasks.docfx-extension-build-task.DocFxTask@0
      displayName: 'Create DocFx Documentation'
      inputs:
        solution: '$(System.DefaultWorkingDirectory)'
        nugetConfigPath: '$(System.DefaultWorkingDirectory)\NuGet.Config'
    - task: AccidentalFish.githubpages-publish.AccidentalFish.GitHubPages-Publish.GitHubPagesPublish@1
      displayName: 'Publishes to GitHub Pages'
      inputs:
        docPath: '$(docPath)'
        githubusername: '$(user)'
        githubemail: '$(email)'
        githubaccesstoken: '$(MGAccessToken)'
        repositoryname: '$(repoName)'
        branchname: '$(branchName)'
        commitmessage: '$(Commit)'