resources:
- repo: self
stages:
- stage: Docfx
  jobs:
  - job: Docfx
    displayName: GithubPagesDocumentation
    pool:
      name: Default
    steps:
    - powershell: |
           $ghPagesPath = "$(System.DefaultWorkingDirectory)\ghpages"
           if (Test-Path -Path $ghPagesPath) {
             Remove-Item –Path $ghPagesPath –Recurse -Force
           }
      displayName: 'Clean Directory'
    - task: UseNode@1
      inputs:
        version: '12.10.0'
    - task: chrismason.vsts-docfxtasks.docfx-extension-build-task.DocFxTask@0
      displayName: 'Create DocFx Documentation'
      inputs:
        solution: '$(System.DefaultWorkingDirectory)'
        nugetConfigPath: '$(System.DefaultWorkingDirectory)\NuGet.Config'
    - task: AccidentalFish.githubpages-publish.AccidentalFish.GitHubPages-Publish.GitHubPagesPublish@1
      displayName: 'Publishes to GitHub Pages'
      inputs:
        docPath: '$(docPath)'
        githubusername: '$(user)'
        githubemail: '$(email)'
        githubaccesstoken: '$(MGAccessToken)'
        repositoryname: '$(repoName)'
        branchname: '$(branchName)'
        commitmessage: '$(Commit)'